kind: pipeline
name: default

steps:

  - name: build test image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t flickr2pelican-tests:${DRONE_COMMIT} -f Dockerfile.tests .

  - name: set permissions
    image: alpine:edge
    commands:
      - chown -Rv 1000:1000 .

  - name: py37
    image: flickr2pelican-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e py37

  - name: flake8
    image: flickr2pelican-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e flake8

  - name: pylint
    image: flickr2pelican-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e pylint

  - name: mypy
    image: flickr2pelican-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e mypy

  - name: black
    image: flickr2pelican-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e black-only-check

  - name: publish
    image: flickr2pelican-tests:${DRONE_COMMIT}
    environment:
      REPO:
        from_secret: REPO
      USERNAME:
        from_secret: USERNAME
      PASSWORD:
        from_secret: PASSWORD
    commands:
      - poetry config repositories.ownrepo $REPO
      - poetry build
      - poetry publish -r ownrepo -u $USERNAME -p $PASSWORD
    when:
      event:
        - tag

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
